spring:
  liquibase:
    enabled: true
    change-log: liquibase/liquibase-changelog.yml
    contexts: default
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pass}

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG